<?php $title = 'Admin Panel'?>
<?php var_dump($data);
?>
<h1 class="text-center">Admin List</h1>
<a href="?page=articles&action=add" class="btn btn-primary m-1">Add Picture</a>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Source</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Author</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($data as $article) : ?>
    <tr>
      <th scope="row"><?= $article['articleID'] ?></th>
      <td><img width="80" src="<?= $article['imagePath'] ?>" alt="<?= $article['title'] ?>"></td>
      <td><?= $article['title'] ?></td>
      <td><?= $article['content'] ?></td>
      <td><?= $article['username'] ?></td>
      <td>
        <a href="?page=admin&action=update&id=<?= $article['articleID'] ?>" class="btn btn-success m-1">Update</a>
        <a href="?page=admin&action=delete&id=<?= $article['articleID'] ?>" class="btn btn-danger m-1">Delete</a>
        <a href="javascript:deletePicture(<?= $article['articleID'] ?>)" class="btn btn-warning m-1">Delete? (confirmJS)</a>
      </td>
    </tr>
  <?php endforeach ?>
  </tbody>
  </table>
  <script>
    function deletePicture(id){
      const question = window.confirm("Are you sure you want to delete "+id+" ?");
      if (question){
        location.href="?page=admin_delete&id="+id;
      }
    }
  </script>
