<?php $title = 'Admin Update Article'?>
<?php var_dump($data);?>

<h1 class="mb-3 text-center">Admin Update Article</h1>
<form method="POST" action="?page=admin_update&id=<?= $id ?>">
<div class="mb-3">
  <label for="title" class="form-label">Title</label>
  <input value="<?= $data['title'] ?>" type="text" class="form-control" name="title" id="title" placeholder="Title">
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <input value="<?= $data['content'] ?>" type="text" class="form-control" name="description" id="description" placeholder="Description">
</div>
<div class="mb-3">
  <label for="src" class="form-label">Source</label>
  <input value="<?= $data['imagePath'] ?>" type="text" class="form-control" name="src" id="src" placeholder="URL Source">
</div>
<div class="mb-3">
  <label for="author" class="form-label">Author</label>
  <input value="<?= $data['username'] ?>" type="text" class="form-control" name="author" id="author" placeholder="Author">
</div>
<div class="mb-3">
  <input type="submit" class="btn btn-primary" name="submit" value="Update Picture">
</div>
</form>