<?php $title = 'Add article Page'?>

<h1>New <article></article></h1>
<?php @var_dump($data)?>


<form method="POST">
<div class="mb-3">
    <label for="imagePath" class="form-label">ImagePath</label>
    <input type="text" class="form-control" id="imagePath" name="imagePath">
  </div>
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" name="title">
  </div>
  <div class="mb-3">
    <label for="content" class="form-label">Content</label>
    <input type="text" class="form-control" id="content" name="content">
  </div>
  <div class="mb-3">
    <label for="authorID" class="form-label">Author ID</label>
    <input type="text" class="form-control" id="authorID" name="authorID">
  </div>

  <button type="submit" class="btn btn-primary mt-3" name="submit" id="send" >Send</button>
</form>